import { IsOptional, IsEnum, IsDateString } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { TimePeriod } from '@/domains/admin/financial-management/dto/revenue-dashboard.dto';

export enum ReportFormat {
  CSV = 'csv',
  EXCEL = 'excel',
  PDF = 'pdf',
  JSON = 'json',
}

export class GenerateFinancialReportDto {
  @ApiProperty({
    enum: TimePeriod,
    description: 'Time period for the report',
  })
  @IsEnum(TimePeriod)
  period: string;

  @ApiPropertyOptional({
    description: 'Start date for custom period',
  })
  @IsOptional()
  @IsDateString()
  startDate?: string;

  @ApiPropertyOptional({
    description: 'End date for custom period',
  })
  @IsOptional()
  @IsDateString()
  endDate?: string;

  @ApiProperty({
    enum: ReportFormat,
    default: ReportFormat.PDF,
    description: 'Output format for the report',
  })
  @IsEnum(ReportFormat)
  format: string = ReportFormat.PDF;
}

export class FinancialReportRevenueByContentTypeDto {
  @ApiProperty({ description: 'Revenue from community memberships' })
  community: number;

  @ApiProperty({ description: 'Revenue from courses' })
  course: number;

  @ApiProperty({ description: 'Revenue from events' })
  event: number;

  @ApiProperty({ description: 'Revenue from products' })
  product: number;

  @ApiProperty({ description: 'Revenue from sessions' })
  session: number;

  @ApiProperty({ description: 'Revenue from challenges' })
  challenge: number;
}

export class FinancialReportRevenueBreakdownDto {
  @ApiProperty({ description: 'Total revenue in the report period' })
  totalRevenue: number;

  @ApiProperty({ description: 'Subscription revenue in the report period' })
  subscriptionRevenue: number;

  @ApiProperty({ description: 'One-time revenue in the report period' })
  oneTimeRevenue: number;

  @ApiProperty({
    description: 'Revenue grouped by content type',
    type: () => FinancialReportRevenueByContentTypeDto,
  })
  revenueByContentType: FinancialReportRevenueByContentTypeDto;
}

export class FinancialReportPayoutsByMethodDto {
  @ApiProperty({ description: 'Payouts sent by bank transfer' })
  bank_transfer: number;

  @ApiProperty({ description: 'Payouts sent by PayPal' })
  paypal: number;

  @ApiProperty({ description: 'Payouts sent by Stripe' })
  stripe: number;
}

export class FinancialReportPayoutSummaryDto {
  @ApiProperty({ description: 'Total payout amount' })
  totalPayouts: number;

  @ApiProperty({ description: 'Completed payout amount' })
  completedPayouts: number;

  @ApiProperty({ description: 'Pending payout amount' })
  pendingPayouts: number;

  @ApiProperty({ description: 'Failed payout amount' })
  failedPayouts: number;

  @ApiProperty({
    description: 'Payout amounts grouped by payout method',
    type: () => FinancialReportPayoutsByMethodDto,
  })
  payoutsByMethod: FinancialReportPayoutsByMethodDto;
}

export class FinancialReportPlatformFeesDto {
  @ApiProperty({ description: 'Total platform fees collected' })
  totalFees: number;

  @ApiProperty({ description: 'Average platform fee percentage' })
  averageFeePercentage: number;

  @ApiProperty({
    description: 'Platform fees grouped by content type',
    type: 'object',
    additionalProperties: { type: 'number' },
  })
  feesByContentType: Record<string, number>;
}

export class FinancialReportTopRevenueCreatorDto {
  @ApiProperty({ description: 'Creator ID' })
  creatorId: string;

  @ApiProperty({ description: 'Creator display name' })
  creatorName: string;

  @ApiProperty({ description: 'Revenue generated by the creator' })
  revenue: number;
}

export class FinancialReportGrowthAnalyticsDto {
  @ApiProperty({ description: 'Revenue growth rate percentage' })
  revenueGrowthRate: number;

  @ApiProperty({ description: 'Transaction growth rate percentage' })
  transactionGrowthRate: number;

  @ApiProperty({ description: 'Average transaction value' })
  averageTransactionValue: number;

  @ApiProperty({
    description: 'Top revenue-generating creators',
    type: () => [FinancialReportTopRevenueCreatorDto],
  })
  topRevenueCreators: FinancialReportTopRevenueCreatorDto[];
}

export class FinancialReportTransactionStatsDto {
  @ApiProperty({ description: 'Total number of transactions' })
  totalTransactions: number;

  @ApiProperty({
    description: 'Transaction count grouped by transaction type',
    type: 'object',
    additionalProperties: { type: 'number' },
  })
  transactionsByType: Record<string, number>;

  @ApiProperty({ description: 'Average transaction value' })
  averageTransactionValue: number;

  @ApiProperty({ description: 'Largest transaction value' })
  largestTransaction: number;
}

export class FinancialReportDto {
  @ApiProperty({ description: 'Report generation timestamp' })
  generatedAt: Date;

  @ApiProperty({ description: 'Report period' })
  period: string;

  @ApiProperty({ description: 'Period start date' })
  startDate: Date;

  @ApiProperty({ description: 'Period end date' })
  endDate: Date;

  @ApiProperty({
    description: 'Revenue breakdown',
    type: () => FinancialReportRevenueBreakdownDto,
  })
  revenueBreakdown: FinancialReportRevenueBreakdownDto;

  @ApiProperty({
    description: 'Payout summary',
    type: () => FinancialReportPayoutSummaryDto,
  })
  payoutSummary: FinancialReportPayoutSummaryDto;

  @ApiProperty({
    description: 'Platform fees collected',
    type: () => FinancialReportPlatformFeesDto,
  })
  platformFees: FinancialReportPlatformFeesDto;

  @ApiProperty({
    description: 'Growth analytics',
    type: () => FinancialReportGrowthAnalyticsDto,
  })
  growthAnalytics: FinancialReportGrowthAnalyticsDto;

  @ApiProperty({
    description: 'Transaction statistics',
    type: () => FinancialReportTransactionStatsDto,
  })
  transactionStats: FinancialReportTransactionStatsDto;
}
