import type { User } from "./models"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    avatar: "/professional-woman-avatar.png",
    role: "creator",
    verified: true,
    communities: [1, 2],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Alex Chen",
    email: "alex@example.com",
    avatar: "/professional-man-avatar.png",
    role: "creator",
    verified: true,
    communities: [3, 4],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
]

export const mockCommunities = [
  {
    id: "1",
    slug: "email-marketing-mastery",
    name: "Email Marketing Mastery",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Master the art of email marketing and grow your business with proven strategies",
    category: "Marketing",
    members: 2847,
    rating: 4.8,
    price: 49,
    priceType: "monthly",
    image: "/email-marketing-dashboard.png",
    tags: ["Email Marketing", "Growth", "Automation", "Strategy"],
    verified: true,
    featured: true,
    type: "community" as const,
  },
  {
    id: "2",
    slug: "brand-design-collective",
    name: "Brand Design Collective",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Join a community of designers creating stunning brand identities",
    category: "Design",
    members: 1523,
    rating: 4.9,
    price: 0,
    priceType: "free",
    image: "/brand-design-workspace.jpg",
    tags: ["Branding", "Design", "Identity", "Creative"],
    verified: true,
    featured: true,
    type: "community" as const,
  },
    {
    id: "11",
    type: "community" as const,
    name: "Email Marketing",
    slug: "email-marketing",
    description: "A community for professionals mastering email marketing strategies and campaigns.",
    category: "Marketing",
    image: "/banners-community/community-1-email-marketing.png",
    creator: "Mohamed Mostafa",
    creatorAvatar: "https://placehold.co/64x64?text=SJ",
    members: 5234,
    rating: 4.9,
    tags: ["Email", "Automation", "Campaigns"],
    price: 29,
    priceType: "monthly",
    verified: true,
    featured: true,
  },
  {
    id: "12",
    type: "community" as const,
    name: "Branding Community",
    slug: "branding-community",
    description: "A community for designers and marketers passionate about building strong brand identities.",
    category: "Design",
    image: "/banners-community/community-2-branding.png",
    creator: "Sarah Johnson",
    creatorAvatar: "https://placehold.co/64x64?text=SJ",
    members: 3456,
    rating: 4.8,
    tags: ["Branding", "Identity", "Strategy"],
    price: 0,
    priceType: "free",
    verified: true,
    featured: true,
  },
  {
    id: "3",
    type: "community" as const,
    name: "Fitness Community",
    slug: "fitness-community",
    description: "A community for fitness enthusiasts to share workouts, nutrition tips, and motivation.",
    category: "Fitness",
    creatorId: "3",
    image: "/banners-community/community-3-fitness.png",
    creator: "Alex Chen",
    creatorAvatar: "https://placehold.co/64x64?text=AC",
    members: 2156,
    rating: 4.7,
    tags: ["Workout", "Health", "Motivation"],
    price: 15,
    priceType: "monthly",
    verified: true,
    featured: true,
  },
  {
    id: "4",
    type: "community" as const,
    name: "Website Vitrine",
    slug: "website-vitrine",
    description: "Design, SEO et conversion pour des sites vitrines simples et efficaces.",
    category: "Web Design",
    image: "/banners-community/community-4-dev.png",
    creator: "Soumaya Chen",
    creatorId: "4",
    creatorAvatar: "https://placehold.co/64x64?text=SC",
    members: 2156,
    rating: 4.7,
    tags: ["Showcase", "UX/UI", "SEO"],
    price: 15,
    priceType: "monthly",
    verified: true,
    featured: true,
  },

  // --- Courses ---
  {
    id: '5',
    type: "course" as const,
    name: "Mastering React",
    slug: "mastering-react",
    description: "An in-depth React course covering hooks, state, and best practices.",
    category: "Development",
    image: "https://placehold.co/600x400?text=React+Course",
    creatorId: "5",
    creator: "Alice Johnson",
    creatorAvatar: "https://placehold.co/64x64?text=AJ",
    members: 340,
    rating: 4.7,
    tags: ["React", "Frontend", "JavaScript"],
    price: 99,
    priceType: "paid",
    verified: true,
    featured: false,
  },
  {
    id: '6',
    type: "course" as const,
    name: "UI/UX Essentials",
    slug: "uiux-essentials",
    description: "Learn the principles of modern UI and UX design with Figma.",
    category: "Design",
    image: "https://placehold.co/600x400?text=UIUX+Course",
    creatorId: "6",
    creator: "Mohamed Ali",
    creatorAvatar: "https://placehold.co/64x64?text=MA",
    members: 220,
    rating: 4.5,
    tags: ["UI", "UX", "Figma"],
    price: 59,
    priceType: "paid",
    verified: false,
    featured: false,
  },

  // --- Challenges ---
  {
    id: '7',
    type: "challenge" as const,
    name: "30 Days of JavaScript",
    slug: "30days-js",
    description: "Daily coding exercises to sharpen your JavaScript skills.",
    category: "Programming",
    image: "https://placehold.co/600x400?text=JS+Challenge",
    creatorId: "5",
    creator: "Sara Lee",
    creatorAvatar: "https://placehold.co/64x64?text=SL",
    members: 500,
    rating: 4.2,
    tags: ["JavaScript", "Frontend", "Coding"],
    price: 0,
    priceType: "free",
    verified: true,
    featured: false,
  },
  {
    id: '8',
    type: "challenge" as const,
    name: "UI Daily Challenge",
    slug: "ui-daily-challenge",
    description: "Design one UI element every day to boost your creativity.",
    category: "Design",
    image: "https://placehold.co/600x400?text=UI+Challenge",
    creatorId: "5",
    creator: "David Kim",
    creatorAvatar: "https://placehold.co/64x64?text=DK",
    members: 280,
    rating: 4.4,
    tags: ["UI", "Design", "Practice"],
    price: 0,
    priceType: "free",
    verified: false,
    featured: false,

  },

  // --- Products ---
  {
    id: '9',
    type: "product" as const,
    name: "IoT Smart Kit",
    slug: "iot-smart-kit",
    description: "A complete kit to build IoT prototypes with sensors and modules.",
    category: "Hardware",
    image: "https://placehold.co/600x400?text=IoT+Kit",
    creatorId: "5",
    creator: "TechStore",
    creatorAvatar: "https://placehold.co/64x64?text=TS",
    members: 0,
    rating: 4.9,
    tags: ["IoT", "Electronics", "Prototyping"],
    price: 199,
    priceType: "paid",
    verified: true,
    featured: false,

  },
  {
    id: '10',
    type: "product" as const,
    name: "UI Components Pack",
    slug: "ui-components-pack",
    description: "A premium set of reusable UI components for modern web apps.",
    category: "Design",
    image: "https://placehold.co/600x400?text=UI+Pack",
    creatorId: "5",
    creator: "DesignHub",
    creatorAvatar: "https://placehold.co/64x64?text=DH",
    members: 0,
    rating: 4.6,
    tags: ["UI", "Components", "Design"],
    price: 49,
    priceType: "paid",
    verified: true,
    featured: false,

  },

  // --- One-to-One ---
  {
    id: '11',
    type: "oneToOne" as const,
    name: "React Mentorship",
    slug: "react-mentorship",
    description: "1:1 mentorship sessions to help you become a React pro.",
    category: "Mentorship",
    image: "https://placehold.co/600x400?text=Mentorship",
    creatorId: "5",
    creator: "Mentor John",
    creatorAvatar: "https://placehold.co/64x64?text=MJ",
    members: 25,
    rating: 5.0,
    tags: ["React", "Mentorship", "Career"],
    price: 50,
    priceType: "hourly",
    verified: true,
    featured: false,

  },
  {
    id: '12',
    type: "oneToOne" as const,
    name: "UI Portfolio Review",
    slug: "ui-portfolio-review",
    description: "Get personalized feedback on your UI/UX portfolio.",
    category: "Design",
    image: "https://placehold.co/600x400?text=Portfolio+Review",
    creator: "Designer Lina",
    creatorAvatar: "https://placehold.co/64x64?text=DL",
    members: 15,
    rating: 4.8,
    tags: ["UI", "UX", "Review"],
    price: 30,
    priceType: "hourly",
    verified: false,
    featured: false,

  },
  
]

export const mockCourses = [
  {
    id: "1",
    slug: "complete-email-marketing",
    name: "Complete Email Marketing Course",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Learn everything from email list building to advanced automation sequences",
    category: "Marketing",
    members: 1247,
    rating: 4.9,
    price: 199,
    priceType: "one-time",
    image: "/email-marketing-course.jpg",
    tags: ["Email", "Marketing", "Automation", "Conversion"],
    verified: true,
    type: "course" as const,
  },
  {
    id: "2",
    slug: "brand-identity-fundamentals",
    name: "Brand Identity Fundamentals",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Master the principles of creating memorable brand identities",
    category: "Design",
    members: 892,
    rating: 4.7,
    price: 149,
    priceType: "one-time",
    image: "/brand-identity-design.png",
    tags: ["Branding", "Design", "Identity", "Logo"],
    verified: true,
    type: "course" as const,
  },
  {
    id: "3",
    slug: "advanced-copywriting",
    name: "Advanced Copywriting Techniques",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Write compelling copy that converts and engages your audience",
    category: "Writing",
    members: 654,
    rating: 4.8,
    price: 179,
    priceType: "one-time",
    image: "/copywriting-workspace.jpg",
    tags: ["Copywriting", "Content", "Marketing", "Sales"],
    verified: true,
    type: "course" as const,
  },
]

export const mockChallenges = [
  {
    id: "1",
    slug: "30-day-email-challenge",
    name: "30-Day Email Growth Challenge",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Grow your email list by 1000+ subscribers in 30 days with daily actionable tasks",
    category: "Marketing",
    members: 456,
    rating: 4.9,
    price: 97,
    priceType: "one-time",
    image: "/email-growth-challenge.jpg",
    tags: ["Challenge", "Email", "Growth", "30 Days"],
    verified: true,
    type: "challenge" as const,
  },
  {
    id: "2",
    slug: "brand-refresh-challenge",
    name: "7-Day Brand Refresh Challenge",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Transform your brand identity in just one week with guided daily exercises",
    category: "Design",
    members: 328,
    rating: 4.8,
    price: 47,
    priceType: "one-time",
    image: "/brand-refresh-design.jpg",
    tags: ["Challenge", "Branding", "Design", "7 Days"],
    verified: true,
    type: "challenge" as const,
  },
]

export const mockEvents = [
  {
    id: "1",
    slug: "email-marketing-summit-2025",
    name: "Email Marketing Summit 2025",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Join industry leaders for a full-day virtual summit on email marketing trends",
    category: "Marketing",
    members: 1847,
    rating: 4.9,
    price: 97,
    priceType: "one-time",
    image: "/virtual-summit-event.jpg",
    tags: ["Event", "Summit", "Email", "Virtual"],
    verified: true,
    type: "event" as const,
  },
  {
    id: "2",
    slug: "brand-design-workshop",
    name: "Brand Design Workshop",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Hands-on workshop to create your brand identity from scratch",
    category: "Design",
    members: 124,
    rating: 5.0,
    price: 197,
    priceType: "one-time",
    image: "/collaborative-design-workshop.png",
    tags: ["Event", "Workshop", "Branding", "In-Person"],
    verified: true,
    type: "event" as const,
  },
]

export const mockSessions = [
  {
    id: "1",
    slug: "email-strategy-consultation",
    name: "Email Strategy Consultation",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Get personalized email marketing strategy and implementation guidance",
    category: "Marketing",
    members: 89,
    rating: 5.0,
    price: 297,
    priceType: "per session",
    image: "/consultation-meeting.jpg",
    tags: ["1-on-1", "Consultation", "Email", "Strategy"],
    verified: true,
    type: "oneToOne" as const,
  },
  {
    id: "2",
    slug: "brand-audit-session",
    name: "Brand Audit & Feedback Session",
    creator: "Sarah Johnson",
    creatorId: "1",
    creatorAvatar: "/professional-woman-avatar.png",
    description: "Comprehensive review of your brand with actionable improvement recommendations",
    category: "Design",
    members: 67,
    rating: 5.0,
    price: 247,
    priceType: "per session",
    image: "/brand-audit-meeting.jpg",
    tags: ["1-on-1", "Audit", "Branding", "Feedback"],
    verified: true,
    type: "oneToOne" as const,
  },
]

export function getCommunitiesByCreator(creatorId: string) {
  return mockCommunities.filter((c) => c.creatorId === creatorId)
}

export function getCoursesByCreator(creatorId: string) {
  return mockCourses.filter((c) => c.creatorId === creatorId)
}

export function getChallengesByCreator(creatorId: string) {
  return mockChallenges.filter((c) => c.creatorId === creatorId)
}

export function getEventsByCreator(creatorId: string) {
  return mockEvents.filter((e) => e.creatorId === creatorId)
}

export function getSessionsByCreator(creatorId: string) {
  return mockSessions.filter((s) => s.creatorId === creatorId)
}

export function getFeatureBySlug(slug: string) {
  const allFeatures = [...mockCommunities, ...mockCourses, ...mockChallenges, ...mockEvents, ...mockSessions]
  return allFeatures.find((f) => f.slug === slug)
}
