"use client"
import { useEffect,useState } from 'react'
import { Sparkles, CalendarRange, Gauge, ArrowUpRight, RefreshCw } from 'lucide-react'
import Link from 'next/link'
import DashSidebar from '@/components/creator-dashboard/DashSidebar'
import DashTopbar from '@/components/creator-dashboard/DashTopbar'
import { creatorWritingApi, type CreatorWritingUsage } from '@/lib/api/creator-writing.api'
import { Button } from '@/components/ui/button'

export default function CreatorUsagePage(){const [usage,setUsage]=useState<CreatorWritingUsage|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);setError('');try{setUsage(await creatorWritingApi.usage())}catch(e:any){setError(e?.message||'Could not load usage.')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);return <div className="flex min-h-screen bg-[var(--bg)]"><DashSidebar/><div className="flex min-h-screen flex-1 flex-col md:ml-[220px]"><DashTopbar title="AI Writing Usage" subtitle="Monitor monthly writing assistance included with your plan"/><main className="mx-auto w-full max-w-5xl flex-1 space-y-6 p-5 sm:p-7">
<section className="overflow-hidden rounded-2xl border border-[var(--bd)] bg-[var(--white)]"><div className="bg-[linear-gradient(120deg,var(--p2),rgba(71,199,234,.12))] p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[var(--p)] text-white"><Sparkles className="h-5 w-5"/></div><h1 className="mt-4 text-2xl font-black text-[var(--t1)]">Creator Writing Assistant</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--t2)]">Generate and improve titles, descriptions and campaign copy directly inside your creator forms.</p></div><Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div></div>
{loading?<div className="p-8 text-sm text-[var(--t3)]">Loading usage...</div>:error?<div className="p-8 text-sm text-red-600">{error}</div>:usage&&<div className="space-y-6 p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-3">{[[Gauge,'Used',usage.used],[Sparkles,'Remaining',usage.remaining],[CalendarRange,'Monthly limit',usage.limit]].map(([Icon,label,value]:any)=><div key={label} className="rounded-xl border border-[var(--bd)] bg-[var(--bg)] p-4"><Icon className="h-5 w-5 text-[var(--p)]"/><p className="mt-3 text-xs font-bold uppercase tracking-wide text-[var(--t3)]">{label}</p><p className="mt-1 text-2xl font-black text-[var(--t1)]">{value}</p></div>)}</div><div><div className="flex items-center justify-between text-sm"><span className="font-semibold text-[var(--t1)]">Monthly usage</span><span className="text-[var(--t3)]">{usage.percentage}%</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[var(--bg)]"><div className="h-full rounded-full bg-[linear-gradient(90deg,var(--p),var(--cyan))]" style={{width:`${usage.percentage}%`}}/></div><p className="mt-2 text-xs text-[var(--t3)]">Resets {new Date(usage.periodEnd).toLocaleDateString()}</p></div><div className="flex flex-col gap-3 rounded-xl border border-[var(--bd)] bg-[var(--bg)] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-[var(--t1)]">Current plan: {usage.plan}</p><p className="text-sm text-[var(--t3)]">Upgrade when you need more monthly generations.</p></div><Button asChild><Link href="/creator/billing">View plans<ArrowUpRight className="ml-2 h-4 w-4"/></Link></Button></div></div>}</section></main></div></div>}
