export const communitiesData = {
  categories: [
    "All",
    "Fitness & Health",
    "Education & Learning",
    "Technology",
    "Business & Entrepreneurship",
    "Creative Arts",
    "Personal Development",
    "Cooking & Food",
    "Travel & Adventure",
    "Music & Entertainment",
  ],
  sortOptions: [
    { value: "popular", label: "Most Popular" },
    { value: "newest", label: "Newest" },
    { value: "members", label: "Most Members" },
    { value: "rating", label: "Highest Rated" },
    { value: "price-low", label: "Price: Low to High" },
    { value: "price-high", label: "Price: High to Low" },
  ],
  communities: [
    {
      id: 1,
      name: "FitLife Transformation",
      creator: "Alex Thompson",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Transform your body and mind with our comprehensive fitness and nutrition program. Join thousands of members on their wellness journey.",
      category: "Fitness & Health",
      members: 2847,
      rating: 4.9,
      price: 29,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Workout Plans", "Nutrition", "Live Sessions", "Community Support"],
      featured: true,
      verified: true,
    },
    {
      id: 2,
      name: "Spanish Mastery Hub",
      creator: "Maria Garcia",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Learn Spanish through immersive conversations, cultural events, and personalized coaching. From beginner to fluent speaker.",
      category: "Education & Learning",
      members: 1923,
      rating: 4.8,
      price: 0,
      priceType: "free",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Language Learning", "Cultural Events", "Live Conversations", "Beginner Friendly"],
      featured: false,
      verified: true,
    },
    {
      id: 3,
      name: "Code Academy Pro",
      creator: "David Kim",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Master programming with hands-on projects, mentorship, and career guidance. 85% job placement rate for graduates.",
      category: "Technology",
      members: 3421,
      rating: 4.9,
      price: 79,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Programming", "Career Support", "Mentorship", "Projects"],
      featured: true,
      verified: true,
    },
    {
      id: 4,
      name: "Entrepreneur's Circle",
      creator: "Sarah Johnson",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Connect with like-minded entrepreneurs, share experiences, and grow your business with expert guidance and peer support.",
      category: "Business & Entrepreneurship",
      members: 1567,
      rating: 4.7,
      price: 49,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Networking", "Business Growth", "Expert Guidance", "Peer Support"],
      featured: false,
      verified: true,
    },
    {
      id: 5,
      name: "Digital Art Studio",
      creator: "Emma Wilson",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Unleash your creativity with digital art tutorials, challenges, and feedback from professional artists and fellow creators.",
      category: "Creative Arts",
      members: 892,
      rating: 4.6,
      price: 19,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Digital Art", "Tutorials", "Art Challenges", "Feedback"],
      featured: false,
      verified: false,
    },
    {
      id: 6,
      name: "Mindful Living Community",
      creator: "Dr. Michael Chen",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Develop mindfulness practices, reduce stress, and create a balanced life through guided meditations and group discussions.",
      category: "Personal Development",
      members: 2156,
      rating: 4.8,
      price: 15,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Mindfulness", "Meditation", "Stress Relief", "Life Balance"],
      featured: true,
      verified: true,
    },
    {
      id: 7,
      name: "Culinary Masters",
      creator: "Chef Isabella Rodriguez",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Master the art of cooking with professional techniques, seasonal recipes, and live cooking sessions with renowned chefs.",
      category: "Cooking & Food",
      members: 1234,
      rating: 4.7,
      price: 25,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Cooking Techniques", "Recipes", "Live Sessions", "Professional Tips"],
      featured: false,
      verified: true,
    },
    {
      id: 8,
      name: "Wanderlust Adventures",
      creator: "Jake Thompson",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Discover hidden gems, plan epic adventures, and connect with fellow travelers. Share stories and get insider travel tips.",
      category: "Travel & Adventure",
      members: 987,
      rating: 4.5,
      price: 0,
      priceType: "free",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Travel Tips", "Adventure Planning", "Travel Stories", "Hidden Gems"],
      featured: false,
      verified: false,
    },
    {
      id: 9,
      name: "Music Production Lab",
      creator: "DJ Alex Martinez",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Learn music production, beat making, and sound design. Get feedback on your tracks and collaborate with other producers.",
      category: "Music & Entertainment",
      members: 1456,
      rating: 4.6,
      price: 39,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Music Production", "Beat Making", "Sound Design", "Collaboration"],
      featured: false,
      verified: true,
    },
    {
      id: 10,
      name: "AI & Machine Learning Hub",
      creator: "Dr. Lisa Wang",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Dive deep into AI and ML concepts, work on real-world projects, and stay updated with the latest developments in artificial intelligence.",
      category: "Technology",
      members: 2789,
      rating: 4.9,
      price: 89,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Artificial Intelligence", "Machine Learning", "Real Projects", "Latest Trends"],
      featured: true,
      verified: true,
    },
    {
      id: 11,
      name: "Yoga & Wellness Sanctuary",
      creator: "Priya Sharma",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Find inner peace through yoga practice, wellness workshops, and holistic health guidance. Suitable for all levels.",
      category: "Fitness & Health",
      members: 1678,
      rating: 4.8,
      price: 22,
      priceType: "monthly",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Yoga", "Wellness", "Holistic Health", "All Levels"],
      featured: false,
      verified: true,
    },
    {
      id: 12,
      name: "Creative Writing Circle",
      creator: "Author Jane Smith",
      creatorAvatar: "/placeholder.svg?height=40&width=40",
      description:
        "Improve your writing skills, share your stories, and get constructive feedback from fellow writers and published authors.",
      category: "Creative Arts",
      members: 743,
      rating: 4.4,
      price: 0,
      priceType: "free",
      image: "/placeholder.svg?height=200&width=300",
      tags: ["Creative Writing", "Story Sharing", "Feedback", "Writing Skills"],
      featured: false,
      verified: false,
    },
  ],
}
